id: P002891
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG21230
  title: རྣམ་ཤེས་ཀྱི་དགོད་སྒྲ།
  author: ''
  volumes:
    e7cd1bad683a4ec1aea5fb2d05b5b0a5:
      image_group_id: I1KG21305
      title: ''
      volume_number: 1
      total_pages: 296
      base_file: v001.txt
