id: P002891
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21230
  title: རྣམ་ཤེས་ཀྱི་དགོད་སྒྲ།
  author: ''
  volumes:
    e7cd1bad683a4ec1aea5fb2d05b5b0a5:
      image_group_id: I1KG21305
      title: ''
      volume_number: 1
      total_pages: 296
