id: I6B56EDAB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:12:00+00:00'
last_modified: '2022-06-07T15:25:34.931202+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21230
  title: རྣམ་ཤེས་ཀྱི་དགོད་སྒྲ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    20A4:
      image_group_id: I1KG21305
      title: ''
      total_pages: 296
      order: 1
      base_file: 20A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
